# Generated by Django 3.2.15 on 2023-01-12 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='country',
            new_name='distr',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='city',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='distr',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(default=models.CharField(max_length=124)),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mob',
            field=models.IntegerField(default='0000000000'),
            preserve_default=False,
        ),
    ]
