# Generated by Django 3.2.15 on 2023-01-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20230112_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.TextField(default='not given')),
                ('mob', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='person',
            name='distr',
        ),
        migrations.DeleteModel(
            name='branches',
        ),
        migrations.DeleteModel(
            name='district',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
